### ISSUE TITLE
[Error report] java.lang.RuntimeException: Cannot invoke (class=LegacyProjectModelListenersBridge, method=changed, topic=WorkspaceModelChangeListener)

### ISSUE THREAD

**Issue by andreasrolke** [vaadin/intellij-plugin#111]
Plugin version: **1.3.3**
IDE version: **IntelliJ IDEA 2024.2.3**
OS: **Windows 11**

Stacktrace:
```
java.lang.RuntimeException: Cannot invoke (class=LegacyProjectModelListenersBridge, method=changed, topic=WorkspaceModelChangeListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:514)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:494)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:471)
	at jdk.proxy2/jdk.proxy2.$Proxy57.changed(Unknown Source)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$onChanged$3$1.invoke(WorkspaceModelImpl.kt:430)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$onChanged$3$1.invoke(WorkspaceModelImpl.kt:429)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.logErrorOnEventHandling(WorkspaceModelImpl.kt:470)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.onChanged(WorkspaceModelImpl.kt:429)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.access$onChanged(WorkspaceModelImpl.kt:44)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$replaceProjectModel$2$2.invoke(WorkspaceModelImpl.kt:375)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl$replaceProjectModel$2$2.invoke(WorkspaceModelImpl.kt:375)
	at com.intellij.platform.workspace.storage.impl.VersionedEntityStorageImpl.replace(VersionedEntityStorageImpl.kt:247)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.replaceProjectModel(WorkspaceModelImpl.kt:375)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.applyLoadedEntities$applyLoadedChanges(JpsProjectModelSynchronizer.kt:195)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.access$applyLoadedEntities$applyLoadedChanges(JpsProjectModelSynchronizer.kt:61)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer$applyLoadedEntities$applyChangesWithRetry$isSuccessful$1.invoke(JpsProjectModelSynchronizer.kt:214)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer$applyLoadedEntities$applyChangesWithRetry$isSuccessful$1.invoke(JpsProjectModelSynchronizer.kt:214)
	at com.intellij.openapi.application.CoroutinesKt$writeAction$2$1.invoke$lambda$0(coroutines.kt:239)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction$lambda$5(AnyThreadWriteThreadingSupport.kt:320)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:328)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:320)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:895)
	at com.intellij.openapi.application.CoroutinesKt$writeAction$2$1.invoke(coroutines.kt:239)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:339)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:232)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:231)
	at com.intellij.openapi.application.CoroutinesKt$writeAction$2.invokeSuspend(coroutines.kt:238)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:44)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:211)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueu
```

**Comment by MarcinVaadin** [comment]
Thanks for creating issue, I don't see anything related to Vaadin plugin in logs. Can you describe the use case that caused this exception?

**Comment by MarcinVaadin** [comment]
Please create new issue providing more details and if possible scenario to reproduce given case.
