### ISSUE TITLE
[Error report] com.intellij.diagnostic.PluginException: Cannot invoke (class=CopilotVaadinProjectListener, method=vaadinProjectDetected, topic=Vaadin project detected) [Plugin: com.vaadin.intellij-plugin]

### ISSUE THREAD

**Issue by Bethibande** [vaadin/intellij-plugin#134]
Plugin version: **1.3.6**
IDE version: **IntelliJ IDEA 2024.2.4**
OS: **Windows 11**

Stacktrace:
```
com.intellij.diagnostic.PluginException: Cannot invoke (class=CopilotVaadinProjectListener, method=vaadinProjectDetected, topic=Vaadin project detected) [Plugin: com.vaadin.intellij-plugin]
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:502)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.RuntimeException: Cannot invoke (class=CopilotVaadinProjectListener, method=vaadinProjectDetected, topic=Vaadin project detected)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:445)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:424)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:483)
	at jdk.proxy22/jdk.proxy22.$Proxy280.vaadinProjectDetected(Unknown Source)
	at com.vaadin.plugin.VaadinProjectDetector.doNotifyAboutVaadinProject(VaadinProjectDetector.kt:31)
	at com.vaadin.plugin.VaadinProjectDetector.execute(VaadinProjectDetector.kt:24)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:496)
	... 6 more
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Write access is allowed inside write-action only (see Application.runWriteAction())

**Comment by MarcinVaadin** [comment]
Thank you for reporting issue, fix is ready, will be available in next release.
