### ISSUE TITLE
[Error report] java.lang.IllegalStateException: vaadin-hotswapagent-runner can only run Java configurations

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/intellij-plugin#188]
Plugin version: **1.4.1**
IDE version: **IntelliJ IDEA 2024.3**
OS: **Mac OS X**

Stacktrace:
```
java.lang.IllegalStateException: vaadin-hotswapagent-runner can only run Java configurations
	at com.vaadin.plugin.hotswapagent.HotswapAgentRunner.execute(HotswapAgentRunner.kt:23)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:831)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$lambda$20$lambda$18(ExecutionManagerImpl.kt:764)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$lambda$20$lambda$19(ExecutionManagerImpl.kt:760)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$7(NonBlockingReadActionImpl.java:734)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:434)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by mdemerat** [comment]
I am also having this issue. I reported to JetBrains 

https://intellij-support.jetbrains.com/hc/en-us/requests/7020533

Here is how you can reproduce the issue. 

Here are some more details about my setup

OS: Sequoia 15.1.1
JDK: OpenJDK 23.0.1 aarch64 (Installed with homebrew)
Quarkus: 3.16.4
IntelliJ: 2024.3 (243.21565.193)
Vaadin plugin 1.4.1
Vaadin Endpoints plugin 243.21565.129

To reproduce follow these instructions. Create a project with this command.
```
quarkus create \
app edu.umich.test:hotswap:0.0.1-SNAPSHOT \
--extension=io.quarkus:quarkus-container-image-docker \
--extension=com.vaadin:vaadin-quarkus-extension
```

Edit the pom.xml. 
In the section <dependencyManagement> move the vaadin pom to be above the quarkus pom
see https://vaadin.com/docs/latest/flow/integrations/quarkus#quarkus.vaadin.knownissues

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
    
Run the application in debug mode with HotswapAgent.

![image](https://github.com/user-attachments/assets/8ff40c02-f43c-4fad-b7f9-3c206a576f18)

When you navigate to localhost:8080 in Chrome and look at the Vaadin copilot I see this error. 

![image](https://github.com/user-attachments/assets/f8fa96a3-c84f-4efd-8450-b2174212d87e)

**Comment by MarcinVaadin** [comment]
Known issue, feature works only with pure Java / Spring boot run configurations.

**Comment by mdemerat** [comment]
Marc, 
OK, it is know issue with Quarkus. Is there a bug request to fix it that I may follow?

**Comment by MarcinVaadin** [comment]
For the moment we will provide more [meaningful message to the users](https://github.com/vaadin/intellij-plugin/pull/197) and try to [hide that option](https://github.com/vaadin/intellij-plugin/issues/184) where incompatible.

There are no plans to provide support for Quarkus for the moment. Feel free to create feature request issue or even contribute with PR.
