### ISSUE TITLE
[Error report] java.lang.NoSuchMethodError: 'boolean com.intellij.java.library.JavaLibraryUtil.hasLibraryClass(com.intellij.openapi.project.Project, java.lang.String)'

### ISSUE THREAD

**Issue by Voldinator** [vaadin/intellij-plugin#200]
Plugin version: **1.4.1**
IDE version: **IntelliJ IDEA 2023.1.7**
OS: **Windows 10**

Stacktrace:
```
java.lang.NoSuchMethodError: 'boolean com.intellij.java.library.JavaLibraryUtil.hasLibraryClass(com.intellij.openapi.project.Project, java.lang.String)'
	at com.vaadin.plugin.utils.VaadinProjectUtilKt.hasVaadin(VaadinProjectUtil.kt:78)
	at com.vaadin.plugin.VaadinProjectDetector.execute$lambda$1(VaadinProjectDetector.kt:27)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.vaadin.plugin.VaadinProjectDetector.execute(VaadinProjectDetector.kt:26)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$runBackgroundPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:467)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(com.intellij.ide.startup.impl.StartupManagerImpl), StandaloneCoroutine{Cancelled}@33b68723, Dispatchers.Default]

```

**Comment by MarcinVaadin** [comment]
You are using outdated version of IntelliJ, please check compatibility matrix https://plugins.jetbrains.com/plugin/23758-vaadin/versions. Did IntelliJ allow you to install that version despite being incompatible?
