### ISSUE TITLE
[Error report] java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.ide.plugins.PluginManagerCore.isPluginInstalled, parameter id

### ISSUE THREAD

**Issue by Mesigit** [vaadin/intellij-plugin#220]
Plugin version: **1.4.2**
IDE version: **IntelliJ IDEA 2024.3.1**
OS: **Windows Server 2022**

Stacktrace:
```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.ide.plugins.PluginManagerCore.isPluginInstalled, parameter id
	at com.intellij.ide.plugins.PluginManagerCore.isPluginInstalled(PluginManagerCore.kt)
	at com.intellij.ide.plugins.PluginManager.isPluginInstalled(PluginManager.java:56)
	at com.vaadin.plugin.utils.VaadinProjectUtilKt.hasEndpoints(VaadinProjectUtil.kt:86)
	at com.vaadin.plugin.ui.VaadinStatusBarWidget.getTooltipText(VaadinStatusBarWidget.kt:50)
	at com.intellij.openapi.wm.impl.status.IconPresentationComponent$1.invoke(IdeStatusBarImpl.kt:982)
	at com.intellij.openapi.wm.impl.status.IconPresentationComponent$1.invoke(IdeStatusBarImpl.kt:982)
	at com.intellij.openapi.wm.impl.status.TextPanel.getToolTipText(TextPanel.kt:56)
	at java.desktop/javax.swing.JComponent.getToolTipText(JComponent.java:3109)
	at com.intellij.ide.IdeTooltipManager.isTooltipDefined(IdeTooltipManager.kt:428)
	at com.intellij.ide.IdeTooltipManager.showForComponent(IdeTooltipManager.kt:389)
	at com.intellij.ide.IdeTooltipManager.maybeShowFor(IdeTooltipManager.kt:376)
	at com.intellij.ide.IdeTooltipManager.eventDispatched$intellij_platform_ide_impl(IdeTooltipManager.kt:296)
	at com.intellij.ide.SwingTooltipManagerCustomizer.execute$lambda$2(IdeTooltipManager.kt:68)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2198)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2089)
	at java.desk
```

**Comment by MarcinVaadin** [comment]
Fixed in 1.4.3
