### ISSUE TITLE
[Error report] java.lang.Throwable: Project location does not match any open project

### ISSUE THREAD

**Issue by ado2000** [vaadin/intellij-plugin#241]
Plugin version: **1.4.3**
IDE version: **IntelliJ IDEA 2024.3.1.1**
OS: **Mac OS X**

Stacktrace:
```
java.lang.Throwable: Project location does not match any open project
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.vaadin.plugin.copilot.service.CopilotRestService.execute(CopilotRestService.kt:48)
	at org.jetbrains.ide.RestService.process(RestService.kt:230)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$checkAndProcess(DelegatingHttpRequestHandler.kt:22)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$0(DelegatingHttpRequestHandler.kt:36)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$1(DelegatingHttpRequestHandler.kt:35)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe$intellij_platform_extensions(ExtensionProcessingHelper.kt:27)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.kt:66)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:97)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:129)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:77)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:23)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.handle(AbstractNioChannel.java:445)
	at io.netty.channel.nio.NioIoHandler$DefaultNioRegistration.handle(NioIoHandler.java:386)
	at io.netty.channel.nio.NioIoHandler.processSelectedKey(NioIoHandler.java:585)
	at io.netty.channel.nio.NioIoHandler.processSelectedKeysOptimized(NioIoHandler.java:560)
	at io.netty.channel.nio.NioIoHandler.processSelectedKeys(NioIoHandler.java:501)
	at io.netty.channel.nio.NioIoHandler.run(NioIoHandler.java:478)
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:184)
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:156)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1123)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.conc
```

**Comment by MarcinVaadin** [comment]
Thanks for reporting, that one is interesting. Can you share your project structure? There is single IntelliJ REST service for all opened projects. Might it be case that you have closed the IDE instance for your running project?

**Comment by ado2000** [comment]
Hi, it could be possible, 

my project is composed of two maven projects.

one used as main library AppFramework ( Vaadin 24.6 ) ( it is not runnable ) 
One as main project ( Vaadin 26.4 ) 

this error happened in the IDE, may be cause I'm trying to make copilot run ( At the moment it does not run ) 

What I see is that in the AppFramework project in the .idea folder I have the file .copilot-plugin but I have not this file in the main project, can it be a problem?

This is the error I see in the main project log.

Any Suggestion?
Thanks

[http-nio-8080-exec-10] ERROR com.vaadin.copilot.ide.CopilotIDEPlugin - Unable to communicate with IDE plugin
java.io.IOException: Unexpected response (400) communicating with the IDE plugin: 
	at com.vaadin.copilot.ide.CopilotIDEPlugin.sendRestSync(CopilotIDEPlugin.java:342)
	at com.vaadin.copilot.ide.CopilotIDEPlugin.send(CopilotIDEPlugin.java:323)
	at com.vaadin.copilot.ide.CopilotIDEPlugin.getModulePaths(CopilotIDEPlugin.java:307)
	at com.vaadin.copilot.JavaSourcePathDetector.detectSourceFoldersUsingIDEPlugin(JavaSourcePathDetector.java:83)
	at com.vaadin.copilot.JavaSourcePathDetector.detectProjectPaths(JavaSourcePathDetector.java:72)
	at com.vaadin.copilot.ProjectFileManager.getProjectPaths(ProjectFileManager.java:362)
	at com.vaadin.copilot.ProjectFileManager.getSourceFolders(ProjectFileManager.java:348)
	at com.vaadin.copilot.ProjectManager.getSourceFolders(ProjectManager.java:180)
	at com.vaadin.copilot.javarewriter.SourceSyncChecker.startSourceFileWatchers(SourceSyncChecker.java:67)
	at com.vaadin.copilot.javarewriter.SourceSyncChecker.<init>(SourceSyncChecker.java:52)
	at com.vaadin.copilot.CopilotSession.<init>(CopilotSession.java:82)
	at com.vaadin.copilot.Copilot.lambda$handleConnect$1(Copilot.java:43)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1066)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2980)
	at com.vaadin.copilot.Copilot.handleConnect(Copilot.java:41)
	at com.vaadin.base.devserver.DebugWindowConnection.handleConnect(DebugWindowConnection.java:208)
	at com.vaadin.base.devserver.DebugWindowConnection.onConnect(DebugWindowConnection.java:188)
	at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$4(PushHandler.java:625)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$5(PushHandler.java:624)
	at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:237)
	at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:621)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:213)
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:254)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:131)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:947)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[http-nio-8080-exec-10] WARN org.atmosphere.websocket.DefaultWebSocketProcessor - Failed invoking AtmosphereFramework.doCometSupport()
java.lang.NullPointerException: Cannot invoke "elemental.json.JsonObject.getObject(String)" because "sourcePathResponse" is null
	at com.vaadin.copilot.JavaSourcePathDetector.detectSourceFoldersUsingIDEPlugin(JavaSourcePathDetector.java:84)
	at com.vaadin.copilot.JavaSourcePathDetector.detectProjectPaths(JavaSourcePathDetector.java:72)
	at com.vaadin.copilot.ProjectFileManager.getProjectPaths(ProjectFileManager.java:362)
	at com.vaadin.copilot.ProjectFileManager.getSourceFolders(ProjectFileManager.java:348)
	at com.vaadin.copilot.ProjectManager.getSourceFolders(ProjectManager.java:180)
	at com.vaadin.copilot.javarewriter.SourceSyncChecker.startSourceFileWatchers(SourceSyncChecker.java:67)
	at com.vaadin.copilot.javarewriter.SourceSyncChecker.<init>(SourceSyncChecker.java:52)
	at com.vaadin.copilot.CopilotSession.<init>(CopilotSession.java:82)
	at com.vaadin.copilot.Copilot.lambda$handleConnect$1(Copilot.java:43)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1066)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2980)
	at com.vaadin.copilot.Copilot.handleConnect(Copilot.java:41)
	at com.vaadin.base.devserver.DebugWindowConnection.handleConnect(DebugWindowConnection.java:208)
	at com.vaadin.base.devserver.DebugWindowConnection.onConnect(DebugWindowConnection.java:188)
	at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$4(PushHandler.java:625)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$5(PushHandler.java:624)
	at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:237)
	at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:621)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:213)
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:254)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:131)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:947)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[http-nio-8080-exec-10] WARN org.atmosphere.websocket.protocol.SimpleHttpProtocol - java.lang.NullPointerException: Cannot invoke "elemental.json.JsonObject.getObject(String)" because "sourcePathResponse" is null. Unable to deliver the websocket messages to installed component. Status 500 Message Server Error
[http-nio-8080-exec-10] WARN org.atmosphere.websocket.DefaultWebSocketProcessor - Failed invoking AtmosphereFramework.doCometSupport()
java.lang.NullPointerException: Cannot invoke "com.vaadin.copilot.CopilotSession.handleMessage(String, elemental.json.JsonObject, com.vaadin.base.devserver.DevToolsInterface)" because the return value of "java.util.Map.get(Object)" is null
	at com.vaadin.copilot.Copilot.handleMessage(Copilot.java:62)
	at com.vaadin.base.devserver.DebugWindowConnection.onMessage(DebugWindowConnection.java:336)
	at com.vaadin.flow.server.communication.PushHandler.handleDebugWindowMessage(PushHandler.java:670)
	at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:237)
	at com.vaadin.flow.server.communication.PushHandler.onMessage(PushHandler.java:646)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:90)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:79)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.lambda$dispatch$2(DefaultWebSocketProcessor.java:326)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:323)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:428)
	at org.atmosphere.container.JSR356Endpoint.lambda$onOpen$2(JSR356Endpoint.java:261)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:130)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:484)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:284)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:184)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:164)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[http-nio-8080-exec-10] WARN org.atmosphere.websocket.protocol.SimpleHttpProtocol - java.lang.NullPointerException: Cannot invoke "com.vaadin.copilot.CopilotSession.handleMessage(String, elemental.json.JsonObject, com.vaadin.base.devserver.DevToolsInterface)" because the return value of "java.util.Map.get(Object)" is null. Unable to deliver the websocket messages to installed component. Status 500 Message Server Error

**Comment by MarcinVaadin** [comment]
Seems like your app project is not recognized as Vaadin project but library project still creates `.copilot-plugin`. Does your app project contain Vaadin dependencies? Vaadin project detection is done via lookup of loaded `com.vaadin.flow.server.VaadinService` class.

**Comment by ado2000** [comment]
Hi, this is a Vaadin application.

here the pom file

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.ado2k</groupId>
    <artifactId>myApp</artifactId>
    <packaging>war</packaging>
    <version>2025</version>
    <name>myApp</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <java.version>17</java.version>
        <vaadin.version>24.6.2</vaadin.version>
    </properties>

    <repositories>
        <repository>
            <id>Vaadin Directory</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.vaadin</groupId>
            <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin</groupId>
                    <artifactId>hilla-dev</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Added to provide logging output as Vaadin uses -->
        <!-- the unbound SLF4J no-operation (NOP) logger implementation -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>


        <!-- App Framework Dependency -->

        <dependency>
            <groupId>com.ado2k</groupId>
            <artifactId>myApp-entity</artifactId>
            <version>2025</version>
        </dependency>

        <dependency>
            <groupId>com.flowingcode.vaadin.addons.chipfield</groupId>
            <artifactId>chipfield-addon</artifactId>
            <!--            <version>2.2.0</version>-->
            <version>2.6.1</version>
            <!--            Sostituire con standard se esiste o con versione 2.6.1-->
        </dependency>

        <dependency>
            <groupId>pl.unforgiven</groupId>
            <artifactId>superfields</artifactId>
            <!--            <version>0.19.0-vaadin14</version>-->
            <version>0.19.2</version>
        </dependency>

        <dependency>
            <groupId>org.parttio</groupId>
            <artifactId>tinymce-for-flow</artifactId>
            <version>4.2.6</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.jchristophe</groupId>
            <artifactId>sortable-layout</artifactId>
            <version>1.1.8</version>
            <!--            Non ci sono aggiornamenti-->
        </dependency>

        <dependency>
            <groupId>org.vaadin.addons.componentfactory</groupId>
            <artifactId>vcf-pdf-viewer</artifactId>
            <!--            <version>1.0.2</version>-->
            <version>4.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.olli</groupId>
            <artifactId>browser-opener</artifactId>
            <!--            <version>0.5</version>-->
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.hilerio</groupId>
            <artifactId>ace-widget</artifactId>
            <!--            <version>1.4.5-Beta</version>-->
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.olli</groupId>
            <artifactId>file-download-wrapper</artifactId>
            <!--            <version>4.0.0</version>-->
            <version>7.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.tabs</groupId>
            <artifactId>paged-tabs</artifactId>
            <!--            <version>3.0.0</version>-->
            <version>4.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaddon</groupId>
            <artifactId>mediaquery</artifactId>
            <!--            <version>4.0.2</version>-->
            <version>5.0.3</version>
        </dependency>

        <!--    Non esiste versione per vaadin 24-->
        <dependency>
            <groupId>org.claspina</groupId>
            <artifactId>confirm-dialog</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>in.virit</groupId>
            <artifactId>viritin</artifactId>
            <version>2.11.2</version>
        </dependency>

        <dependency>
            <groupId>com.github.appreciated</groupId>
            <artifactId>apexcharts</artifactId>
            <!--            <version>2.0.0-beta13</version>-->
            <version>24.0.2</version>
        </dependency>


        <!--        Fine componenti vaadin-->

        <!--        Non vaadin library -->

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>compile</scope>
        </dependency>

        <!-- langchain4j-->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
            <version>0.36.2</version>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
            <version>0.36.2</version>
        </dependency>
        <!-- End langchain4j-->

        <!-- Gestione della cache -->
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <version>3.9.11</version>
        </dependency>

        <!-- Fine della gestione della cache -->

        <!-- inizio dipendenze conversione in pdf-->

        <dependency>
            <groupId>com.github.scribejava</groupId>
            <artifactId>scribejava-apis</artifactId>
            <version>8.3.3</version>
        </dependency>

        <!-- Apache POI per la gestione di documenti DOCX -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.3.0</version> <!-- Verifica la versione più recente su Maven Central -->
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.3.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/fr.opensagres.xdocreport/fr.opensagres.poi.xwpf.converter.pdf -->
        <dependency>
            <groupId>fr.opensagres.xdocreport</groupId>
            <artifactId>fr.opensagres.poi.xwpf.converter.pdf</artifactId>
            <version>2.0.4</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.18.0</version>
        </dependency>

        <dependency>
            <groupId>hr.ngs.templater</groupId>
            <artifactId>templater</artifactId>
            <!--            <version>7.2.1</version>-->
            <version>7.3.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.vibur</groupId>
            <artifactId>vibur-dbcp</artifactId>
            <version>25.0</version>
        </dependency>

        <dependency>
            <groupId>org.mnode.ical4j</groupId>
            <artifactId>ical4j</artifactId>
            <version>3.2.11</version>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <!--            <version>30.1-jre</version>-->
            <version>33.3.0-jre</version>
            <!-- 05/04/19 <version>23.0</version> -->
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <!-- 05/04/19 <version>2.8.2</version> -->
            <!-- 06/02/2024 <version>2.8.5</version>-->
            <version>2.10.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/dnsjava/dnsjava -->
        <dependency>
            <groupId>dnsjava</groupId>
            <artifactId>dnsjava</artifactId>
            <!--            <version>3.5.3</version>-->
            <version>3.6.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.24.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.24.3</version>
        </dependency>


        <!-- https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>9.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <!--            <version>20170516</version>-->
            <version>20240303</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.springframework/spring-core -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>6.2.1</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.springframework/spring-beans -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>6.2.1</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jdt.core.compiler</groupId>
            <artifactId>ecj</artifactId>
            <version>4.6.1</version>
        </dependency>

        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <version>10.0.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- Usato per webservices rest -->

        <!-- https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api -->
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>4.0.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.glassfish.jersey.bundles/jaxrs-ri -->
        <dependency>
            <groupId>org.glassfish.jersey.bundles</groupId>
            <artifactId>jaxrs-ri</artifactId>
            <!--            <version>2.43</version>-->
            <version>3.1.9</version>
            <!--            <version>4.0.0-M1</version>-->
        </dependency>

        <!--        jackson backup-->

        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
            <!--            <version>2.12.5</version>-->
            <version>2.18.2</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310 -->
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <!--            <version>2.12.5</version>-->
            <version>2.18.2</version>
        </dependency>

        <dependency>
            <groupId>com.github.dpaukov</groupId>
            <artifactId>combinatoricslib3</artifactId>
            <!--            <version>3.3.1</version>-->
            <version>3.4.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>0.12.6</version>
        </dependency>

        <!-- Vaadin 24 addons -->

        <dependency>
            <groupId>org.vaadin.stefan</groupId>
            <artifactId>html-table</artifactId>
            <version>1.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.stefan</groupId>
            <artifactId>fullcalendar2</artifactId>
            <version>6.2.2</version>
        </dependency>

        <dependency>
            <groupId>org.vaadin.stefan</groupId>
            <artifactId>fullcalendar2-scheduler</artifactId>
            <version>6.2.2</version>
        </dependency>

        <!-- Carosello-->
        <dependency>
            <groupId>com.flowingcode.addons.carousel</groupId>
            <artifactId>carousel-addon</artifactId>
            <version>3.0.0</version>
        </dependency>


    </dependencies>

    <build>
        <!--        <defaultGoal>spring-boot:run</defaultGoal>-->
        <defaultGoal>jetty:run</defaultGoal>
        <plugins>

            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <profiles>
        <profile>
            <!-- Production mode is activated using -Pproduction -->
            <id>production</id>
            <dependencies>
                <!-- Exclude development dependencies from production -->
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>vaadin</artifactId>
                    <exclusions>
                        <exclusion>
                            <groupId>com.vaadin</groupId>
                            <artifactId>hilla-dev</artifactId>
                        </exclusion>
                    </exclusions>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>build-frontend</goal>
                                </goals>
                                <phase>compile</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
