### ISSUE TITLE
[Error report] com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.vaadin.plugin.copilot.action.ToggleServerAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.vaadin.intellij-plugin]

### ISSUE THREAD

**Issue by IhorTarkhan** [vaadin/intellij-plugin#28]
Plugin version: **1.0.4**
IDE version: **IntelliJ IDEA 2024.1**
OS: **Mac OS X**

Stacktrace:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.vaadin.plugin.copilot.action.ToggleServerAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.vaadin.intellij-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by MarcinVaadin** [comment]
Thank you for reporting issue, I will try to include it in incoming release.
