### ISSUE TITLE
[Error report] java.lang.IllegalStateException: vaadin-hotswapagent-runner needs a module

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/intellij-plugin#85]
Plugin version: **1.3.0**
IDE version: **IntelliJ IDEA 2024.1**
OS: **Mac OS X**

Stacktrace:
```
java.lang.IllegalStateException: vaadin-hotswapagent-runner needs a module
	at com.vaadin.plugin.hotswapagent.HotswapAgentRunner.execute(HotswapAgentRunner.kt:25)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:809)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:761)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$default(ExecutionManagerImpl.kt:713)
	at com.intellij.execution.impl.ExecutionManagerImpl$restartRunProfile$1.run(ExecutionManagerImpl.kt:611)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:253)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1152)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:123)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by abdullahtellioglu** [comment]
Logs before the stack trace: 

```java
2024-09-12 10:54:49,268 [79767892]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning completed for copilot. Number of scanned files: 4098; number of files for indexing: 117 took 91ms; general responsiveness: ok; EDT responsiveness: ok
2024-09-12 10:54:49,270 [79767894]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: UnindexedFilesScanner[copilot, 39 iterators]
2024-09-12 10:54:49,270 [79767894]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.util.indexing.DumbModeWhileScanningTrigger$DumbModeWhileScanning@14b76d32
2024-09-12 10:54:49,271 [79767895]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) UnindexedFilesIndexer[copilot, 3 iterators, reason: changes in: "Module 'copilot-client-test-flow-nohilla-noreact' (all roots)", "Module 'copilot' (annotations, java, java, resources, resources, test-annotations)", "Module 'copilot-project' (dist, generated, generated, generated)", "Library Maven: com.github.javaparser:javaparser-symbol-solver-core:3.26.2 (#1 class roots, #0 source roots)", "Library Maven: com.vaadin:flow-html-components:24.5.0.alpha18 (#1 class roots, #0 source roots)", "Library Maven: com.vaadin:flow-test-generic:24.5.0.alpha18 (#1 class roots, #0 source roots)", "Library Maven: com.vaadin:hilla-endpoint:24.5.0.alpha14 (#1 class roots, #0 source roots)", "Library Maven: com.vaadin:ui-tests:1.0.0.alpha5 (#1 class roots, #0 source roots)", "Library Maven: com.vaadin:vaadin-accordion-flow:24.5.0.alpha16 (#1 class roots, #0 source roots)", "Library Maven: com.vaadin:vaadin-avatar-flow:24.5.0.alpha16 (#1 class roots, #0 source roots)" and 29 iterators more]
2024-09-12 10:54:49,271 [79767895]   INFO - #c.i.u.i.c.IndexUpdateRunner - Using 7 indexing and 4 writing threads for indexing
2024-09-12 10:54:51,280 [79769904] SEVERE - #c.i.u.c.QueueProcessor - vaadin-hotswapagent-runner needs a module
java.lang.IllegalStateException: vaadin-hotswapagent-runner needs a module
```

**Comment by Artur-** [comment]
Is there something like ”indexing complete” afterwards?
